Repository Link-zip/Link-zip-FE, pull requests merged in 2024-07, with the labels that each got.

#4 [ADD/#3] drawerbtn 추가
  app/src/main/res/drawable/drawerbtn_allselect_selected.xml
  app/src/main/res/drawable/drawerbtn_lineup_early_selected.xml
  app/src/main/res/drawable/drawerbtn_lineup_early_unselected.xml
  app/src/main/res/drawable/drawerbtn_lineup_ganada_selected.xml
  app/src/main/res/drawable/drawerbtn_lineup_ganada_unselected.xml
  app/src/main/res/drawable/drawerbtn_lineup_old_selected.xml
  app/src/main/res/drawable/drawerbtn_lineup_old_unselected.xml
  app/src/main/res/drawable/drawerbtn_lineup_visit_selected.xml
  app/src/main/res/drawable/drawerbtn_lineup_visit_unselected.xml
  app/src/main/res/drawable/drawerbtn_linkselect_selected.xml
  app/src/main/res/drawable/drawerbtn_textlinkselect_selected.xml
Labels: :heavy_plus_sign: ADD, :baby_chick: 누누

#11 [Feat/#5] 바텀내비게이션 구현
  .idea/migrations.xml
  .idea/misc.xml
  app/src/main/java/umc/link/zip/presentation/MainActivity.kt
  app/src/main/res/color/bottom_nav_item_selector_font.xml
  app/src/main/res/color/bottom_nav_item_selector_item.xml
  app/src/main/res/drawable/bottom_nav_selector_home.xml
  app/src/main/res/drawable/bottom_nav_selector_list.xml
  app/src/main/res/drawable/bottom_nav_selector_mypage.xml
  app/src/main/res/drawable/bottom_nav_selector_zip.xml
  app/src/main/res/drawable/btn_bottomnav_back.xml
  app/src/main/res/drawable/btn_bottomnav_create.xml
  app/src/main/res/drawable/shadow_bottom_nav.xml
  app/src/main/res/drawable/shadow_bottom_nav_create.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#18 [Feat/#16] 마이페이지 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/link/zip/presentation/mypage/CornerView.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageProfileFragment.kt
  app/src/main/res/drawable/bg_mypage_boxinfo.xml
  app/src/main/res/drawable/bg_mypage_profile_bg1.png
  app/src/main/res/drawable/bg_mypage_profile_bg2.png
  app/src/main/res/drawable/bg_mypage_profile_bggra1.xml
  app/src/main/res/drawable/bg_mypage_profile_bggra2.xml
  app/src/main/res/drawable/bg_mypage_profile_btn_dup.xml
  app/src/main/res/drawable/bg_mypage_profile_btn_save.xml
  app/src/main/res/drawable/bg_mypage_profile_et.xml
  app/src/main/res/drawable/bg_transparent.xml
  app/src/main/res/drawable/blur_mypage_profile.xml
  app/src/main/res/drawable/btn_mypage_setting_alarm.xml
  app/src/main/res/drawable/btn_mypage_withdrawal.xml
  app/src/main/res/drawable/ic_main_alarm_nothing.xml
  app/src/main/res/drawable/ic_mypage_clip.png
  app/src/main/res/drawable/ic_mypage_detail.xml
  app/src/main/res/drawable/ic_mypage_kakao.xml
  app/src/main/res/drawable/ic_mypage_logo.png
  app/src/main/res/drawable/ic_mypage_profile_back.xml
  app/src/main/res/drawable/ic_mypage_setting_alarm_bg.xml
  app/src/main/res/drawable/shadow_bluebtn.png
  app/src/main/res/drawable/shadow_mypage_bg.xml
  app/src/main/res/drawable/toggle_mypage_setting_alarm.xml
  app/src/main/res/drawable/view_mypage_bg.xml
  app/src/main/res/drawable/view_mypage_social_bg.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_list_rv.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/fragment_mypage_setting.xml
  app/src/main/res/layout/fragment_mypage_withdrawal.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_notice_detail.xml
  app/src/main/res/layout/item_link.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: :paintbrush: UI, :baby_chick: 누누

#19 [Feat/#13] home 페이지 구현
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/res/drawable/bg_home_gradient1.png
  app/src/main/res/drawable/bg_home_gradient2.png
  app/src/main/res/drawable/bg_home_recommend.png
  app/src/main/res/drawable/ic_gnb_details.xml
  app/src/main/res/drawable/ic_home_rarrow.xml
  app/src/main/res/drawable/ic_main_search.xml
  app/src/main/res/drawable/img_home_likelink.png
  app/src/main/res/drawable/img_home_logo.png
  app/src/main/res/drawable/img_home_oldlink.png
  app/src/main/res/drawable/img_home_recent.png
  app/src/main/res/drawable/img_home_recommend.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_recent.xml
  app/src/main/res/layout/item_home_recommend.xml
  app/src/main/res/values/themes.xml
Labels: :paintbrush: UI, :raccoon: 쿠우

#21 [Feat/#10] splash 페이지 구현
  app/src/main/res/drawable/img_loading_logo.png
  app/src/main/res/layout/activity_splash.xml
Labels: :paintbrush: UI, :raccoon: 쿠우

#22 [Feat/#9] 프로필 설정 페이지 구현
  app/src/main/res/drawable/ic_deletex.xml
  app/src/main/res/drawable/ic_gnb_back.xml
  app/src/main/res/drawable/img_profilesetcompleted_3dhand.png
  app/src/main/res/drawable/shadow_graybtn.png
  app/src/main/res/drawable/shape_profileset_edittext.xml
  app/src/main/res/drawable/shape_rect_8_1191ad_fill.xml
  app/src/main/res/drawable/shape_rect_8_666666_fill.xml
  app/src/main/res/drawable/shape_rect_8_white_fill_d9d9d9_line.xml
  app/src/main/res/layout/fragment_profileset.xml
  app/src/main/res/layout/fragment_profilesetcompleted.xml
  app/src/main/res/values/styles.xml
Labels: :paintbrush: UI, :raccoon: 쿠우
