Repository Link-zip/Link-zip-FE, pull requests merged in 2024-08, with the labels that each got.

#36 [Feat/#31] home recyclerview
  .idea/vcs.xml
  app/src/main/java/umc/link/zip/domain/model/Link.kt
  app/src/main/java/umc/link/zip/domain/model/Zip.kt
  app/src/main/java/umc/link/zip/presentation/base/BaseActivity.kt
  app/src/main/java/umc/link/zip/presentation/home/AlarmFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/RecentRVAdapter.kt
  app/src/main/java/umc/link/zip/presentation/home/SharedViewModel.kt
  app/src/main/res/drawable/img_home_recent2.png
  app/src/main/res/drawable/img_home_recent3.png
  app/src/main/res/drawable/img_home_recent4.png
  app/src/main/res/drawable/img_home_recommend1.png
  app/src/main/res/drawable/img_home_recommend2.png
  app/src/main/res/drawable/img_home_recommend3.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_recent.xml
  app/src/main/res/layout/item_home_recommend.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :sparkles: Feat, :raccoon: 쿠우

#38 [Feat/#33] 프로필 설정 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/link/zip/presentation/SplashActivity.kt
  app/src/main/java/umc/link/zip/presentation/base/BaseActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetCompletedFragment.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetFragment.kt
  app/src/main/res/drawable/shape_profileset_edittext_able.xml
  app/src/main/res/drawable/shape_profileset_edittext_default.xml
  app/src/main/res/drawable/shape_profileset_edittext_disable.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_profileset.xml
  app/src/main/res/layout/fragment_profilesetcompleted.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/colors.xml
Labels: :sparkles: Feat, :raccoon: 쿠우

#39 [Feat/#29] 리스트 리사이클러뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/link/zip/domain/model/List/Link.kt
  app/src/main/java/umc/link/zip/domain/model/List/Zip.kt
  app/src/main/java/umc/link/zip/presentation/base/BaseBottomSheetDialogFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListDialogueLineupFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListDialogueListselectFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadLineDialogSharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadListDialogSharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/adapter/ListUnreadRVA.kt
  app/src/main/java/umc/link/zip/presentation/list/adapter/ListVPA.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageSettingFragment.kt
  app/src/main/java/umc/link/zip/util/extension/ColorHelper.kt
  app/src/main/java/umc/link/zip/util/extension/StatusExtension.kt
  app/src/main/java/umc/link/zip/util/extension/StringExt.kt
  app/src/main/res/layout/fragment_dialogue_lineup.xml
  app/src/main/res/layout/fragment_dialogue_listselect.xml
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_list_rv.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/fragment_mypage_setting.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_notice_detail.xml
  app/src/main/res/layout/item_link.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/xml/network_security_config.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#40 [Feat/#34] Mypage 화면 연결
  app/src/main/java/umc/link/zip/domain/model/notice/Notice.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageProfileFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageProfileViewModel.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageSettingFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageWithdrawalFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/NicknameState.kt
  app/src/main/java/umc/link/zip/presentation/mypage/NoticeDetailFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/NoticeFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/adapter/NoticeRVA.kt
  app/src/main/java/umc/link/zip/util/extension/CharExt.kt
  app/src/main/java/umc/link/zip/util/extension/KeyboardUtil.kt
  app/src/main/res/drawable/bg_mypage_profile_btn_dup_active.xml
  app/src/main/res/drawable/toggle_mypage_setting_alarm_no.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/fragment_mypage_setting.xml
  app/src/main/res/layout/fragment_mypage_withdrawal.xml
  app/src/main/res/layout/fragment_notice.xml
  app/src/main/res/layout/fragment_notice_detail.xml
  app/src/main/res/layout/item_notice.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#42 [Feat/#27] alarm 기능 개발
  app/build.gradle.kts
  app/src/main/java/umc/link/zip/domain/model/alarm/Alarm.kt
  app/src/main/java/umc/link/zip/presentation/base/BaseFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/AlarmFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/alarm/AlarmFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/alarm/AlarmViewModel.kt
  app/src/main/java/umc/link/zip/presentation/home/alarm/adapter/AlarmRVA.kt
  app/src/main/res/drawable/shape_rect_gradiant_down.xml
  app/src/main/res/drawable/shape_rect_gradiant_up.xml
  app/src/main/res/layout/fragment_alarm.xml
  app/src/main/res/layout/fragment_customtext_alarm.xml
  app/src/main/res/layout/fragment_customtext_memo.xml
  app/src/main/res/layout/fragment_open_link.xml
  app/src/main/res/layout/fragment_open_text.xml
  app/src/main/res/layout/fragment_savelink_alarm.xml
  app/src/main/res/layout/fragment_savelink_custom.xml
  app/src/main/res/layout/fragment_savelink_memo.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/layout/item_alarm_ad.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :sparkles: Feat, :rabbit2: 반희

#45 [Fix/#44] 마이페이지 투명 상태바 적용 해결
  app/src/main/java/umc/link/zip/presentation/base/BaseActivity.kt
  app/src/main/res/layout/fragment_list.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: :lady_beetle: FIX, :baby_chick: 누누

#48 [Feat/#46] home - list 탭 연결
  app/src/main/java/umc/link/zip/domain/model/list/Link.kt
  app/src/main/java/umc/link/zip/domain/model/list/Zip.kt
  app/src/main/java/umc/link/zip/presentation/MainActivity.kt
  app/src/main/java/umc/link/zip/presentation/home/AlarmFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListDialogueLineupFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListDialogueListselectFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListTabViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadLineDialogSharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadListDialogSharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/adapter/ListUnreadRVA.kt
  app/src/main/java/umc/link/zip/presentation/list/adapter/ListViewModel.kt
  app/src/main/res/layout/fragment_list.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#54 [Feat/#41] 로그인 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/link/zip/LinkZipApplication.kt
  app/src/main/java/umc/link/zip/data/AuthInterceptor.kt
  app/src/main/java/umc/link/zip/data/dto/request/LoginRequest.kt
  app/src/main/java/umc/link/zip/data/dto/response/LoginResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/LoginService.kt
  app/src/main/java/umc/link/zip/di/NetworkModule.kt
  app/src/main/java/umc/link/zip/di/RepositoryModule.kt
  app/src/main/java/umc/link/zip/di/ServiceModule.kt
  app/src/main/java/umc/link/zip/domain/model/home/Link.kt
  app/src/main/java/umc/link/zip/domain/model/home/Zip.kt
  app/src/main/java/umc/link/zip/domain/model/login/LoginModel.kt
  app/src/main/java/umc/link/zip/domain/repository/LoginRepository.kt
  app/src/main/java/umc/link/zip/presentation/MainActivity.kt
  app/src/main/java/umc/link/zip/presentation/SplashActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/AuthCodeHandlerActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginViewModel.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetCompletedFragment.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetFragment.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  settings.gradle.kts
Labels: :sparkles: Feat, :raccoon: 쿠우

#59 [Feat/#55] Login API
  app/src/main/java/umc/link/zip/data/dto/BaseResponse.kt
  app/src/main/java/umc/link/zip/data/dto/request/SignupRequest.kt
  app/src/main/java/umc/link/zip/data/dto/response/JwtResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/LoginResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/NameCheckResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/SignupResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/LoginService.kt
  app/src/main/java/umc/link/zip/domain/model/login/JwtModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/LoginModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/NameCheckModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/SignupModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/TokenModel.kt
  app/src/main/java/umc/link/zip/domain/repository/LoginRepository.kt
  app/src/main/java/umc/link/zip/presentation/SplashActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginViewModel.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetFragment.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetViewModel.kt
Labels: :sparkles: Feat, :raccoon: 쿠우

#62 [Feat/#60] Logout + 기타 자잘한 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/umc/link/zip/data/UserPreferences.kt
  app/src/main/java/umc/link/zip/data/dto/BaseResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/NameCheckResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/LoginService.kt
  app/src/main/java/umc/link/zip/domain/model/login/NameCheckModel.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageFragment.kt
  app/src/main/res/layout/fragment_profileset.xml
Labels: :lady_beetle: FIX, :sparkles: Feat, :raccoon: 쿠우

#66 [Feat/#47] Home API
  app/src/main/java/umc/link/zip/data/dto/BaseResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeAlertCountResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeAlertExistsResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeOldCountResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeRecentResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeTotalCountResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/HomeUnreadCountResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/HomeRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/HomeService.kt
  app/src/main/java/umc/link/zip/di/RepositoryModule.kt
  app/src/main/java/umc/link/zip/di/ServiceModule.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeAlertCountModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeAlertExistsModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeOldCountModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeRecentModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeTotalCountModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/HomeUnreadCountModel.kt
  app/src/main/java/umc/link/zip/domain/model/home/Link.kt
  app/src/main/java/umc/link/zip/domain/model/home/Zip.kt
  app/src/main/java/umc/link/zip/domain/repository/HomeRepository.kt
  app/src/main/java/umc/link/zip/presentation/MainActivity.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeViewModel.kt
  app/src/main/java/umc/link/zip/presentation/home/RecentRVAdapter.kt
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/res/drawable/img_default_thumbnail.png
  app/src/main/res/drawable/img_home_recent.png
  app/src/main/res/drawable/img_home_recent2.png
  app/src/main/res/drawable/img_home_recent3.png
  app/src/main/res/drawable/img_home_recent4.png
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home_recent.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :sparkles: Feat, :raccoon: 쿠우

#68 [FIX/#65] home -> list 연결 오류 해결
  app/src/main/java/umc/link/zip/presentation/home/SharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/home/search/SearchFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListLikeFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListRecentFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListTabViewModel.kt
  app/src/main/java/umc/link/zip/presentation/list/ListUnreadFragment.kt
Labels: :lady_beetle: FIX, :baby_chick: 누누

#72 [feat/#71] 회원탈퇴 api 구현
  app/src/main/java/umc/link/zip/data/dto/mypage/response/WithdrawalResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/MypageRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/MypageService.kt
  app/src/main/java/umc/link/zip/domain/model/mypage/WithdrawalModel.kt
  app/src/main/java/umc/link/zip/domain/repository/MypageRepository.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageWithdrawalFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageWithdrawalViewModel.kt
Labels: :sparkles: Feat, :baby_chick: 누누

#73 [Feat/#67] 토큰 갱신 API
  app/src/main/java/umc/link/zip/data/AuthInterceptor.kt
  app/src/main/java/umc/link/zip/data/UserPreferences.kt
  app/src/main/java/umc/link/zip/data/dto/TokenAuthenticator.kt
  app/src/main/java/umc/link/zip/data/dto/request/LoginRequest.kt
  app/src/main/java/umc/link/zip/data/dto/request/RefreshRequest.kt
  app/src/main/java/umc/link/zip/data/dto/response/LoginResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/RefreshResponse.kt
  app/src/main/java/umc/link/zip/data/dto/response/SignupResponse.kt
  app/src/main/java/umc/link/zip/data/repositoryImpl/LoginRepositoryImpl.kt
  app/src/main/java/umc/link/zip/data/service/LoginService.kt
  app/src/main/java/umc/link/zip/di/NetworkModule.kt
  app/src/main/java/umc/link/zip/domain/model/login/RefreshModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/SignupModel.kt
  app/src/main/java/umc/link/zip/domain/model/login/TokenModel.kt
  app/src/main/java/umc/link/zip/domain/repository/LoginRepository.kt
  app/src/main/java/umc/link/zip/presentation/SplashActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/LoginActivity.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetFragment.kt
  app/src/main/java/umc/link/zip/presentation/login/ProfilesetViewModel.kt
Labels: :sparkles: Feat, :raccoon: 쿠우

#78 [FEAT/#75] bottom navigation tab 이동 시 화면 초기화
  app/src/main/java/umc/link/zip/data/dto/TokenAuthenticator.kt
  app/src/main/java/umc/link/zip/presentation/MainActivity.kt
Labels: :sparkles: Feat, :raccoon: 쿠우

#80 [Feat/#74] app icon 적용
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/layout/fragment_openzip.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#89 [FIX/#88] 토큰 갱신 만료 시간 오류 수정
  app/src/main/java/umc/link/zip/data/dto/TokenAuthenticator.kt
Labels: :lady_beetle: FIX, :raccoon: 쿠우

#90 [Feat/#85] zip 링크개수 연동
  .idea/other.xml
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextZipItemAdapter.kt
  app/src/main/java/umc/link/zip/presentation/home/alert/AlertViewModel.kt
  app/src/main/java/umc/link/zip/presentation/zip/OpenZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/ZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipItemAdapter.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipMoveDialogAdapter.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipMoveDialogFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipMoveDialogSharedViewModel.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/ZipAlertViewModel.kt
  app/src/main/res/layout/fragment_openzip.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :lady_beetle: FIX, :chipmunk: 마로

#91 [Feat/#87] 알림 api 추가
  app/build.gradle.kts
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListViewModel.kt
  app/src/main/java/umc/link/zip/presentation/zip/OpenZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipItemAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :sparkles: Feat, :baby_chick: 누누

#95 Feat/#92 zip 부가적인 부분 2차 수정
  app/src/main/java/umc/link/zip/presentation/zip/OpenZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/ZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/OpenZipItemAdapter.kt
  app/src/main/java/umc/link/zip/presentation/zip/adapter/ZipAlertViewModel.kt
  app/src/main/res/drawable/canclebtn.xml
  app/src/main/res/drawable/canclebtn2.xml
  app/src/main/res/layout/fragment_deletelink.xml
  app/src/main/res/layout/fragment_deletezip.xml
Labels: :lady_beetle: FIX, :heavy_plus_sign: ADD, :chipmunk: 마로

#102 [Feat/#101] enter key 기능 추가 및 오류 수정
  app/src/main/java/umc/link/zip/presentation/create/CreateFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/alert/AlertFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/search/SearchFragment.kt
  app/src/main/res/layout/fragment_makezip.xml
  app/src/main/res/layout/fragment_mypage_profile.xml
  app/src/main/res/layout/fragment_search.xml
Labels: :lady_beetle: FIX, :sparkles: Feat, :baby_chick: 누누

#105 [Mod/#103] timeout 및 각종 오류 해결
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextZipItemAdapter.kt
  app/src/main/java/umc/link/zip/presentation/create/ModifylinkCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/ModifylinkMemoFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/ModifytextAlarmFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/ModifytextCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/ModifytextMemoFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenLinkFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenTextFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/adapter/LinkAddViewModel.kt
  app/src/main/res/navigation/main_graph.xml
Labels: :lady_beetle: FIX, :baby_chick: 누누

#108 [Feat] zip 만들기 기능 추가
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/EditZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/MakeZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/ZipFragment.kt
  app/src/main/res/layout/fragment_customlink_zip.xml
  app/src/main/res/layout/fragment_customtext_zip.xml
  app/src/main/res/layout/fragment_editzip.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :lady_beetle: FIX, :sparkles: Feat, :chipmunk: 마로

#110 [FIX/#106] 검색 페이지 링크 이동 오류 수정
  app/src/main/java/umc/link/zip/presentation/home/search/SearchFragment.kt
Labels: :lady_beetle: FIX, :baby_chick: 누누

#111 [Fix/#97] 뒤로가기 오류 / WebView > Chrome
  .idea/other.xml
  app/build 4/outputs 2/logs/manifest-merger-debug-report.txt
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextCustomFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/CustomtextZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenLinkFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenTextFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/WebViewFragment.kt
  app/src/main/res/layout/fragment_web_view.xml
  app/src/main/res/navigation/main_graph.xml
Labels: :lady_beetle: FIX, :rabbit2: 반희

#113 [REFACTOR/#112] 간편저장 로직 수정
  app/src/main/java/umc/link/zip/presentation/create/CustomlinkZipFragment.kt
Labels: :axe: REFACTOR, :rabbit2: 반희

#117 [FIX/#116] refresh 기능 fragment에 추가
  app/src/main/java/umc/link/zip/presentation/create/CreateFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenLinkFragment.kt
  app/src/main/java/umc/link/zip/presentation/create/OpenTextFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/HomeFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/alert/AlertFragment.kt
  app/src/main/java/umc/link/zip/presentation/home/search/SearchFragment.kt
  app/src/main/java/umc/link/zip/presentation/list/ListFragment.kt
  app/src/main/java/umc/link/zip/presentation/mypage/MypageFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/OpenZipFragment.kt
  app/src/main/java/umc/link/zip/presentation/zip/ZipFragment.kt
Labels: :lady_beetle: FIX, :baby_chick: 누누
